In [1]:
import pandas as pd
import json
from datetime import datetime

In [2]:
with open('..\datasets\custos_importacao.json', 'r', encoding='utf-8') as f:
    dados = json.load(f)

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\jhiovana.ribeiro\AppData\Local\Temp\ipykernel_2548\4109013537.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  with open('..\datasets\custos_importacao.json', 'r', encoding='utf-8') as f:

In [3]:
# Normalizar os dados
df = pd.json_normalize(
    dados,
    record_path=['historic_data'],
    meta=['product_id', 'product_name', 'category']
)

df.head()

   start_date  usd_price product_id                 product_name     category
0  10/08/2016   10583.63          1  Transponder AIS Maré Magnum  eletrônicos
1  15/06/2018    8778.36          1  Transponder AIS Maré Magnum  eletrônicos
2  25/09/2018    8023.87          1  Transponder AIS Maré Magnum  eletrônicos
3  19/03/2019    8772.78          1  Transponder AIS Maré Magnum  eletrônicos
4  17/01/2020    7918.18          1  Transponder AIS Maré Magnum  eletrônicos

In [5]:
# Reorganizar as ordem das colunas
df = df[['product_id', 'product_name', 'category', 'start_date', 'usd_price']]
df.head()

  product_id                 product_name     category  start_date  usd_price
0          1  Transponder AIS Maré Magnum  eletrônicos  10/08/2016   10583.63
1          1  Transponder AIS Maré Magnum  eletrônicos  15/06/2018    8778.36
2          1  Transponder AIS Maré Magnum  eletrônicos  25/09/2018    8023.87
3          1  Transponder AIS Maré Magnum  eletrônicos  19/03/2019    8772.78
4          1  Transponder AIS Maré Magnum  eletrônicos  17/01/2020    7918.18