## Questão 3 - Custo de Importação

### Cenário

Além dos dados de produtos, Gabriel percebeu também que o arquivo `custos_importacao.json` tem todos os dados historicos dos preços de compra aninhados num único campo. Para
facilitar a análise dessa informação no banco de dados é necessário melhorarmos isso.

### Premissas obrigatóriao

- Utilize apenas o JSON `custos_importacao.json`
- Utilize obrigatoriamente Python 3

Tarefa:

- Carregue o arquivo JSON e gere um novo arquivo CSV organizando-o de acordo com a definição na imagem abaixo.

| custo_importacao |  |
| --- | --- |
| product_id | integer |
| product_name | text |
| category | text |
| start_date | date |
| usd_date | float |

In [1]:
import pandas as pd
import json

In [2]:
with open('..\datasets\custos_importacao.json', 'r', encoding='utf-8') as f:
    dados_custos = json.load(f)

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\jhiovana.ribeiro\AppData\Local\Temp\ipykernel_11648\1637712238.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  with open('..\datasets\custos_importacao.json', 'r', encoding='utf-8') as f:

In [4]:
# Convertendo a coluna 'start_date' para o formato datetime
df['start_date'] = pd.to_datetime(df['start_date'], format='%d/%m/%Y', errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1260 non-null   int64
 1   product_name  1260 non-null   object
 2   category      1260 non-null   object
 3   start_date    1260 non-null   datetime64[ns]
 4   usd_price     1260 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 49.3+ KB

In [5]:
df['start_date'] = pd.to_datetime(df['start_date'], dayfirst=True, errors='coerce')
# Verificação
print(f"Total de NaTs encontrados: {df['start_date'].isna().sum()}")

Total de NaTs encontrados: 0

In [6]:
df.head()

   product_id                 product_name     category start_date  usd_price
0           1  Transponder AIS Maré Magnum  eletrônicos 2016-08-10   10583.63
1           1  Transponder AIS Maré Magnum  eletrônicos 2018-06-15    8778.36
2           1  Transponder AIS Maré Magnum  eletrônicos 2018-09-25    8023.87
3           1  Transponder AIS Maré Magnum  eletrônicos 2019-03-19    8772.78
4           1  Transponder AIS Maré Magnum  eletrônicos 2020-01-17    7918.18

In [21]:
# Salvando a base normalizada para uso nas próximas análises
df.to_csv('..\datasets\custos_importacao.csv', index=False)

<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\jhiovana.ribeiro\AppData\Local\Temp\ipykernel_40400\1230832279.py:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df.to_csv('..\datasets\custos_importacao.csv', index=False)

In [7]:
with open('..\datasets\custos_importacao.json', 'r', encoding='utf-8') as f:
    dados = json.load(f)

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\jhiovana.ribeiro\AppData\Local\Temp\ipykernel_11648\585573642.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  with open('..\datasets\custos_importacao.json', 'r', encoding='utf-8') as f:

In [ ]:
linhas = []
 
# Normalização dos dados para estrutura tabular
for produto in dados: 
    for registro in produto["historic_data"]:
        linhas.append({
            "product_id":   produto["product_id"],
            "product_name": produto["product_name"],
            "category":     produto["category"],
            "start_date":   registro["start_date"]
            "usd_price":    registro["usd_price"],
        })
 
df_custos = pd.DataFrame(linhas)
df_custos.head()

   product_id                 product_name     category  start_date  usd_price
0           1  Transponder AIS Maré Magnum  eletrônicos  10/08/2016   10583.63
1           1  Transponder AIS Maré Magnum  eletrônicos  15/06/2018    8778.36
2           1  Transponder AIS Maré Magnum  eletrônicos  25/09/2018    8023.87
3           1  Transponder AIS Maré Magnum  eletrônicos  19/03/2019    8772.78
4           1  Transponder AIS Maré Magnum  eletrônicos  17/01/2020    7918.18

In [16]:
# Ajuste dos tipos de dados
df_custos["product_id"] = df_custos["product_id"].astype(int)
df_custos["product_name"] = df_custos["product_name"].astype(str)
df_custos["category"] = df_custos["category"].astype(str)
df_custos["start_date"] = pd.to_datetime(df_custos["start_date"], format="%d/%m/%Y")
df_custos["usd_price"] = df_custos["usd_price"].astype(float)
print(df_custos.dtypes)

product_id               int64
product_name            object
category                object
start_date      datetime64[ns]
usd_price              float64
dtype: object

In [17]:
df_custos.head()

   product_id                 product_name     category start_date  usd_price
0           1  Transponder AIS Maré Magnum  eletrônicos 2016-08-10   10583.63
1           1  Transponder AIS Maré Magnum  eletrônicos 2018-06-15    8778.36
2           1  Transponder AIS Maré Magnum  eletrônicos 2018-09-25    8023.87
3           1  Transponder AIS Maré Magnum  eletrônicos 2019-03-19    8772.78
4           1  Transponder AIS Maré Magnum  eletrônicos 2020-01-17    7918.18

In [13]:
df_custos['category'].unique()

array(['eletrônicos', 'propulsão', 'ancoragem'], dtype=object)

In [14]:
df_custos['category'].value_counts()

category
eletrônicos    436
ancoragem      413
propulsão      411
Name: count, dtype: int64

In [19]:
df_custos.isnull().sum()

product_id      0
product_name    0
category        0
start_date      0
usd_price       0
dtype: int64

In [20]:
df_custos.duplicated().sum()

np.int64(0)

In [18]:
print("-" * 50)
print("  custos_importacao — resultado")
print("-" * 50)
print(f"  Linhas geradas : {len(df)}")
print(f"  Produtos únicos: {df['product_id'].nunique()}")
print()
print(df_custos.dtypes)
print()
print(df_custos.head(10).to_string(index=False))

--------------------------------------------------
  custos_importacao — resultado
--------------------------------------------------
  Linhas geradas : 1260
  Produtos únicos: 150

product_id               int64
product_name            object
category                object
start_date      datetime64[ns]
usd_price              float64
dtype: object

 product_id                product_name    category start_date  usd_price
          1 Transponder AIS Maré Magnum eletrônicos 2016-08-10   10583.63
          1 Transponder AIS Maré Magnum eletrônicos 2018-06-15    8778.36
          1 Transponder AIS Maré Magnum eletrônicos 2018-09-25    8023.87
          1 Transponder AIS Maré Magnum eletrônicos 2019-03-19    8772.78
          1 Transponder AIS Maré Magnum eletrônicos 2020-01-17    7918.18
          1 Transponder AIS Maré Magnum eletrônicos 2020-06-17    6310.01
          1 Transponder AIS Maré Magnum eletrônicos 2021-07-02    6586.70
          1 Transponder AIS Maré Magnum eletrônicos 2022-05-16    6538.20
          1 Transponder AIS Maré Magnum eletrônicos 2023-02-28    6360.91
          1 Transponder AIS Maré Magnum eletrônicos 2023-10-17    6574.80

In [23]:
pd.concat([df.head(5), df_custos.tail(5)])

,product_id,product_name,category,start_date,usd_price
0,1,Transponder AIS Maré Magnum,eletrônicos,2016-08-10,10583.63
1,1,Transponder AIS Maré Magnum,eletrônicos,2018-06-15,8778.36
2,1,Transponder AIS Maré Magnum,eletrônicos,2018-09-25,8023.87
3,1,Transponder AIS Maré Magnum,eletrônicos,2019-03-19,8772.78
4,1,Transponder AIS Maré Magnum,eletrônicos,2020-01-17,7918.18
1255,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,2023-06-01,326.88
1256,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,2024-01-31,332.26
1257,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,2024-08-29,292.03
1258,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,2024-10-04,300.96
1259,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,2024-10-25,288.90

In [2]:
# Salvando a base normalizada para uso nas próximas análises
df_custos.to_csv('..\datasets\custos_importacao.csv', index=False)
print("\nArquivo salvo → custos_importacao.csv ✓")

<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\jhiovana.ribeiro\AppData\Local\Temp\ipykernel_21488\3417413548.py:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df_custos.to_csv('..\datasets\custos_importacao.csv', index=False)
C:\Users\jhiovana.ribeiro\AppData\Local\Temp\ipykernel_21488\3417413548.py:2: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df_custos.to_csv('..\datasets\custos_importacao.csv', index=False)

NameError: name 'df_custos' is not defined