## Questão 3 - Custo de Importação

### Cenário

Além dos dados de produtos, Gabriel percebeu também que o arquivo `custos_importacao.json` tem todos os dados historicos dos preços de compra aninhados num único campo. Para
facilitar a análise dessa informação no banco de dados é necessário melhorarmos isso.

### Premissas obrigatóriao

- Utilize apenas o JSON `custos_importacao.json`
- Utilize obrigatoriamente Python 3

Tarefa:

- Carregue o arquivo JSON e gere um novo arquivo CSV organizando-o de acordo com a definição na imagem abaixo.

| custo_importacao |  |
| --- | --- |
| product_id | integer |
| product_name | text |
| category | text |
| start_date | date |
| usd_date | float |

In [1]:
import pandas as pd
import json

In [5]:
with open('../datasets/raw/custos_importacao.json', 'r', encoding='utf-8') as f:
    dados = json.load(f)

In [6]:
# Normalizar os dados
df = pd.json_normalize(
    dados,
    record_path=['historic_data'],
    meta=['product_id', 'product_name', 'category']
)

df.head()

   start_date  usd_price product_id                 product_name     category
0  10/08/2016   10583.63          1  Transponder AIS Maré Magnum  eletrônicos
1  15/06/2018    8778.36          1  Transponder AIS Maré Magnum  eletrônicos
2  25/09/2018    8023.87          1  Transponder AIS Maré Magnum  eletrônicos
3  19/03/2019    8772.78          1  Transponder AIS Maré Magnum  eletrônicos
4  17/01/2020    7918.18          1  Transponder AIS Maré Magnum  eletrônicos

In [7]:
# Reorganizar as ordem das colunas
df = df[['product_id', 'product_name', 'category', 'start_date', 'usd_price']]
df.head()

  product_id                 product_name     category  start_date  usd_price
0          1  Transponder AIS Maré Magnum  eletrônicos  10/08/2016   10583.63
1          1  Transponder AIS Maré Magnum  eletrônicos  15/06/2018    8778.36
2          1  Transponder AIS Maré Magnum  eletrônicos  25/09/2018    8023.87
3          1  Transponder AIS Maré Magnum  eletrônicos  19/03/2019    8772.78
4          1  Transponder AIS Maré Magnum  eletrônicos  17/01/2020    7918.18

In [10]:
print(df.dtypes)

product_id       object
product_name     object
category         object
start_date       object
usd_price       float64
dtype: object

In [11]:
# Ajuste dos tipos de dados
df["product_id"] = df["product_id"].astype(int)
df["product_name"] = df["product_name"].astype(str)
df["category"] = df["category"].astype(str)
df["start_date"] = pd.to_datetime(df["start_date"], format="%d/%m/%Y")
df["usd_price"] = df["usd_price"].astype(float)
print(df.dtypes)

product_id               int64
product_name            object
category                object
start_date      datetime64[ns]
usd_price              float64
dtype: object

In [12]:
df['category'].unique()

array(['eletrônicos', 'propulsão', 'ancoragem'], dtype=object)

In [13]:
df['category'].value_counts()

category
eletrônicos    436
ancoragem      413
propulsão      411
Name: count, dtype: int64

In [14]:
info_custos = pd.DataFrame({
    "Duplicados": df.duplicated().sum(),
    "Nulos": df.isnull().sum(),
    "Tipo de Dados": df.dtypes,
    "Valores Únicos": df.nunique()
})

info_custos

              Duplicados  Nulos   Tipo de Dados  Valores Únicos
product_id             0      0           int64             150
product_name           0      0          object             150
category               0      0          object               3
start_date             0      0  datetime64[ns]             985
usd_price              0      0         float64            1258

In [15]:
display(df)

,product_id,product_name,category,start_date,usd_price
0,1,Transponder AIS Maré Magnum,eletrônicos,2016-08-10,10583.63
1,1,Transponder AIS Maré Magnum,eletrônicos,2018-06-15,8778.36
2,1,Transponder AIS Maré Magnum,eletrônicos,2018-09-25,8023.87
3,1,Transponder AIS Maré Magnum,eletrônicos,2019-03-19,8772.78
4,1,Transponder AIS Maré Magnum,eletrônicos,2020-01-17,7918.18
...,...,...,...,...,...
1255,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,2023-06-01,326.88
1256,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,2024-01-31,332.26
1257,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,2024-08-29,292.03
1258,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,2024-10-04,300.96
1259,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,2024-10-25,288.90

In [16]:
print("          Visão Geral")
print("-"*30)
print(f"Linhas geradas : {len(df)}")
print(f"Produtos únicos: {df['product_id'].nunique()}\n")
print(f"Máximo  : {df['usd_price'].max()}")
print(f"Mínimo  : {df['usd_price'].min()}")
print(f"Média   : {df['usd_price'].mean()}")
print("-"*30)
print()
print("        Tipos dos Dados")
print("-"*30)
print(df.dtypes)

          Visão Geral
------------------------------
Linhas geradas : 1260
Produtos únicos: 150

Máximo  : 48583.21
Mínimo  : 53.37
Média   : 7890.234785714286
------------------------------

        Tipos dos Dados
------------------------------
product_id               int64
product_name            object
category                object
start_date      datetime64[ns]
usd_price              float64
dtype: object

In [18]:
# Salvando a base normalizada para uso nas próximas análises
df.to_csv('../datasets/processed/custos_importacao.csv', index=False)
print("\nArquivo salvo → custos_importacao.csv ")

Arquivo salvo → custos_importacao.csv